version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: ig-iap-tunnel
    main: .
    binary: ig-iap-tunnel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/retailnext/ig-iap-tunnel/app.Version={{.Version}}
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
